# Generated by Django 4.2.6 on 2024-02-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreciclaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Baterias'), (2, 'Organico'), (3, 'Papel'), (4, 'Plastico'), (5, 'Vidrio')]),
        ),
    ]
